### ISSUE TITLE
Updated/Replaced ongoing alert shows incorrectly expired

### ISSUE THREAD

**Issue by srichter** [qconrad/severe-weather-alerts#1]
I noticed that an alert which is ongoing and has been updated will incorrectly show as expired. For instance the following "Tropical Storm Warning" alert shows as expired with "Updated 4 hours ago" and "Exited area 4 hours ago", when it is in fact still active: https://api.weather.gov/alerts/urn:oid:2.49.0.1.840.0.da1670036d7b7224eb49d0268dd57eac665fe93f.004.1

I believe it may be due to the alert being replaced by a broader alert ~15 minutes after it was posted, but for some reason the broader alert doesn't appear in the app: https://api.weather.gov/alerts/urn:oid:2.49.0.1.840.0.bce1505fce98033793cd0ff6e88b6574daa1fd60.001.1

Let me know if you need any debug info from me. Thanks for the continued work on this app.

**Comment by qconrad** [comment]
Sorry I didn't notice this post earlier but I'll look deeper into this. The exited area comes from filtering for polygon warnings where the only indication a polygon has been updated to not include an area is that there is a replacement that doesn't exist in the alert list. I think this is what is causing the bug. I appreciate the report and I'll try and get this fixed.

**Comment by srichter** [comment]
Thanks for looking into this. I have copies of the linked alerts if you'd like them for debugging purposes.

**Comment by qconrad** [comment]
If you could send me those, that would be super helpful!

**Comment by srichter** [comment]
[json.zip](https://github.com/qconrad/severe-weather-alerts/files/6987218/json.zip)

(Odd that GitHub doesn't let you attach .json files)

**Comment by qconrad** [comment]
Appreciate the alerts! I believe have a fix working that will be out next release so I'm closing this issue for now. Thanks again!
