### ISSUE TITLE
Allow alert text to be selectable

### ISSUE THREAD

**Issue by srichter** [qconrad/severe-weather-alerts#2]
I think it would be beneficial to allow the user to select/copy text from an alert. I don't have an Android dev environment set up, so I can't play around with this, but I believe it should be as simple as adding `android:textIsSelectable="true"` to the relevant TextViews defined in `res/layout/alert_viewer.xml`

**Comment by qconrad** [comment]
Thanks for the suggestion! I'll for sure add this in a future update. Also considering some kind of share or copy to clipboard option.
